from tkinter import *
def calculate():
    #print("Aie!")
    #print("The double of ",e.get()," is ",2*int(e.get()))
    x=float(e.get())
    v.set(str(2*x))
window=Tk()
window.title("Double")
l1=Label(window,text="x")
l1.grid(row=0,column=0)
e=Entry(window,bg="yellow")
e.grid(row=0,column=1)
l1=Label(window,text="x^2")
l1.grid(row=1,column=0)
e1=Entry(window,bg="cyan")
e1.grid(row=1,column=1)
b1=Button(window,text="Quit",command=quit)
b1.grid(row=2,column=0)
b2=Button(window,text="Calculate",command=calculate)
b2.grid(row=2,column=2)
v=StringVar()
l3=Label(window,textvariable=v)
l3.grid(row=1,column=1)
window.mainloop()