from tkinter import *
def calculate():
    a=float(e1.get())
    b=float(e2.get())
    c=float(e3.get())
    delta=float((b**2)-(4*a*c))
    v.set(str(delta))
    if(delta>0):
        x1=float((-b+(delta**0.5))/2*a)
        x2=float((-b-(delta**0.5))/2*a)
        v1.set(str(x1))
        v2.set(str(x2))
    if(delta==0):
        x1=float(-b/2*a)
        v1.set(str(x1))
    if(delta<0):
        x1=float((-b+(delta**0.5))/2*a)
        x2=float((-b-(delta**0.5))/2*a)
        v1.set(str(x1))
        v2.set(str(x2))
window=Tk()
window.title("Second-Degree")
l1=Label(window,text="a : ")
l1.grid(row=0,column=0)
e1=Entry(window,bg="pink")
e1.grid(row=0,column=1)
l2=Label(window,text="b : ")
l2.grid(row=1,column=0)
e2=Entry(window,bg="cyan")
e2.grid(row=1,column=1)
l3=Label(window,text="c : ")
l3.grid(row=2,column=0)
e3=Entry(window,bg="pink")
e3.grid(row=2,column=1)
l4=Label(window,text="Delta : ")
l4.grid(row=3,column=0)
v=StringVar()
l5=Label(window,textvariable=v)
l5.grid(row=3,column=1)
b1=Button(window,text="Quit",command=quit)
b1.grid(row=4,column=0)
b2=Button(window,text="Calculate",command=calculate)
b2.grid(row=4,column=2)
l6=Label(window,text="Solutions : ")
l6.grid(row=5,column=0)
v1=StringVar()
l7=Label(window,textvariable=v1)
l7.grid(row=5,column=1)
v2=StringVar()
l8=Label(window,textvariable=v2)
l8.grid(row=6,column=1)
window.mainloop()