from tkinter import *
from math import *
def EquiRectDistDeg():
    lat1=float(e1.get())
    lon1=float(e2.get())
    lat2=float(e3.get())
    lon2=float(e4.get())
    la1=float(lat1*0.0174533)
    lo1=float(lon1*0.0174533)
    la2=float(lat2*0.0174533)
    lo2=float(lon2*0.0174533)
    calculate(la1,lo1,la2,lo2)
def calculate(la1,lo1,la2,lo2):
    #la1=float(e1.get())
    #lo1=float(e2.get())
    #la2=float(e3.get())
    #lo2=float(e4.get())
    r=6371000
    y =float(la2-la1)
    x =float(lo2-lo1)*cos((la1+la2)/2)
    d=sqrt(pow(x,2)+pow(y,2))*r
    v.set(str(d))
window=Tk()
window.title("Distance")
l1=Label(window,text="Latitude 1 : ")
l1.grid(row=0,column=0)
e1=Entry(window,bg="pink")
e1.grid(row=0,column=1)
l2=Label(window,text="Longitude 1 : ")
l2.grid(row=1,column=0)
e2=Entry(window,bg="cyan")
e2.grid(row=1,column=1)
l3=Label(window,text="Latitude 2 : ")
l3.grid(row=2,column=0)
e3=Entry(window,bg="pink")
e3.grid(row=2,column=1)
l4=Label(window,text="Longitude 2 : ")
l4.grid(row=3,column=0)
e4=Entry(window,bg="cyan")
e4.grid(row=3,column=1)
b1=Button(window,text="Quit",command=quit,bg="beige")
b1.grid(row=4,column=0)
b2=Button(window,text="Calculate",command=EquiRectDistDeg,bg="beige")
b2.grid(row=4,column=2)
v=StringVar()
l5=Label(window,textvariable=v)
l5.grid(row=5,column=1)
l6=Label(window,text="Distance(in m) : ")
l6.grid(row=5,column=0)
window.mainloop()